### ISSUE TITLE
Insecure Proxy

### ISSUE THREAD

**Issue by FliKites** [imperviousinc/fingertip#20]
Could an option be added to allow for fingertip to be used over a secure local proxy?

**Comment by buffrr** [comment]
Can you explain your use case in more detail and what you mean by "secure local proxy"? Do you have a web/HTTPS proxy that you want Fingertip to use as an upstream?

**Comment by FliKites** [comment]
I'm just opening an issue based on what I saw [in this thread.](https://news.namebase.io/post/4495) The OP never opened an issue, so I thought I would.  Trying to determine if its possible for a user to set an https:// proxy vs an http:// proxy. My understanding is using a secure proxy would stop the data from being sent upstream unencrypted? But would degrade performance I'm guessing?

**Comment by buffrr** [comment]
Well, that's not how Fingertip works. The "http" proxy is a local server listening at 127.0.0.1 it never leaves your device and even then HTTPS connections are encrypted. So no it's not sent "upstream unencrypted" that would make it useless. Just because the proxy url uses http it doesn't mean that it isn't proxying HTTPS connections. Listening over https doesn't make any sense here.
