### ISSUE TITLE
No guide to setup fingertip on chrome

### ISSUE THREAD

**Issue by ChristianOConnor** [imperviousinc/fingertip#31]
How do I configure chrome to work with fingertip? I can only find a guide on how to do that for Firefox. Chrome doesn't seem to have a proxy setting

**Comment by rithvikvibhu** [comment]
Unlike Firefox, Chrome always uses the OS' proxy settings which depends on the OS.

If on Windows, there's an Auto Configure option (right click on the fingertip icon in the taskbar -> auto configure) which will set everything up automatically.

Otherwise, the setup page ("help" from taskbar) shows instructions on what proxy to set manually.

**Comment by ChristianOConnor** [comment]
Okay cool thanks for explaining!
